 # 配置语言及相应版本
language: node_js

node_js:
  - "4"

# 项目所在分支
branches:
    only:
    - master

# 配置环境
before_install:
    # 替换为刚才生成的解密信息
    - openssl aes-256-cbc -K $encrypted_1bfd95de1409_key -iv $encrypted_1bfd95de1409_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
    # 改变文件权限
    - chmod 600 ~/.ssh/id_rsa 
    # 配置 ssh
    - eval $(ssh-agent)
    - ssh-add ~/.ssh/id_rsa
    - cp .travis/ssh_config ~/.ssh/config
    # 配置 git 替换为自己的信息
    - git config user.name "pvphero"
    - git config user.email impvphero@163.com
    
# 安装依赖
install:
    - npm install hexo-cli -g
    - npm install
    
# 部署的命令
script:
    - npm run deploy  # hexo clean && hexo g -d

after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "pvphero"
    - git config user.email "impvphero@163.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${travis_token}@${GH_REF}" master:master

    

env:
 global:
   - GH_REF: github.com/pvphero/pvphero.github.io.git
   - secure: "RThxgHfChkKEloJyw5nCdDZMnjjzgh7ulzP4MhjEgNXg2rRGWnMCp2GT/Zy1Jr7gZ8Qn/rLGo99vdRCC7GFBNTjucVPfL+WGZQ/1Ub0WGNPT+vxgrn+GiEJkKLcUQpJMrqK8cFNU9Zo4qOecmDMM7VBoprZG51JH45xQTFXi40S7MJvE3yR1hWE3rauKVZH1vBcqPhwzCRXVRmq1OmfER7602ecs13q+AGpu007VXpM3nS56GyZygt5dieXHi1Q3IEuutVOcCpJPFXFs33/Dg+aJXt9yTF6uyLQiZ4n1+hiPsVc9gHbd5XJDegRzEHN8OuzumZayquR7KWet/GrNeDIMUcFWF+V6dmmQnrUEvH89lSWrUSx31S6rWLSOT5Xt2IoUM+T0SpGgXCkt9UVSBkqA9DrHuyt/OCv/ghglp8R0zxJVAybsVLUR9HQn8J3kBdn4zG/vjWzOsryK5SOIekVurPQ9tpxGreO36wK247zRK+PlmtZv8k94MZyr0FcuQP/6Mq1kEru220EE++xkILZJWYQVLslsHKTAbj/DjrgErXyKcqqV66ZiewY70+K987gvvoQEqMiNRk4xIjzYU//cX6fet9Gl0i0dSJ2wFbkZNQRmMjuZy627fGAXLVzbivy/rvg04zGra+On7/QS77OO5wRNuJGRBkWxNBdwdCY="